# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xlgo_3Elw5S6LOWs1DHHXWbV2Axd7AbM
"""

import transformers
import torch
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
from transformers import AutoModelForSeq2SeqLM
from transformers import pipeline
import spacy

class Information_Retrieval:
  '''
  Given stringy text, this class allows various functions to retrieve 
  information.
  '''
  def __init__(corpus, QAandSum_model, transITA_model, transEN_model):
    self.corpus=corpus
    self.QAandSum_model = AutoModelForQuestionAnswering.from_pretrained(QAandSum_model)
    self.QAandSum_tokenizer = AutoTokenizer.from_pretrained(QAandSum_model)
    self.translationITA_model = AutoModelForSeq2SeqLM.from_pretrained (transITA_model)
    self.translationITA_tokenizer = AutoTokenizer.from_pretrained(transITA_model)
    self.traslationEN_model = AutoModelForSeq2SeqLM.from_pretrained (transEN_model)
    self.translationEN_tokenizer = AutoTokenizer.from_pretrained(transEN_model)

  def QA_Bert (QAandSum_model,corpus,question):
    '''
    Through the use of a pre-trained model belonging to the Transformers library, 
    the function allows the extraction of information from an unstructured 
    natural language text.
    '''
    nlp = pipeline("question-answering")
    result = nlp(question=question, context=corpus)
    return [result['answer'], round(result['score'], 4)] #Vogliamo inserire la threshold ?

  def summarize_Bert (QAandSum, corpus, max_length, min_length): #130/30
    '''
    this function provides a summary of the text in natural language. 
    It is possible to establish the length parameters through 'max_lenght' and 
    'min_lenght'
    '''
    summarizer = pipeline("summarization")
    summary = summarizer(corpus, max_length, min_length, do_sample=False)
    return summary[0]['summary_text']

  def translationITA_Bert (transITA_model, corpus):
    '''
    This function allows the translation of the text from English to Italian.
    '''
    nlp = spacy.load('en_core_web_sm')
    translationITA_tokenizer = transITA_model
    corpus=[str(sent) for sent in nlp(corpus).sents]
    translator_it = pipeline("translation_en_to_it", model=transITA_model, tokenizer=translationITA_tokenizer) 
    translation = translator_it(corpus,max_length=4000)
    translation = ' '.join(v for ele in translation for v in ele.values())
    return translation

  def translationEN_Bert (transEN_model,corpus):
    '''
    This function allows the translation of the text from Italian to English.
    '''
    nlp = spacy.load('it_core_news_sm')
    translationEN_tokenizer = transEN_model
    corpus=[str(sent) for sent in nlp(corpus).sents]
    translator_en = pipeline("translation_it_to_en", model=transEN_model, tokenizer=translationEN_tokenizer) 
    translation = translator_en(corpus, max_length=4000)
    translation = ' '.join(v for ele in translation for v in ele.values())
    return translation


if __name__ == '__main__':

  #Models used for summary, translation and QA
  modello_QAandSum="bert-large-uncased-whole-word-masking-finetuned-squad"
  modello_ITATranslation = "Helsinki-NLP/opus-mt-en-it"
  modello_ENTranslation = "Helsinki-NLP/opus-mt-it-en"

  #Exemple of texts to processed
  text=""" Mary is the most prominent figure in the composition, taking up much of the center of the image.[4] She sits directly on the ground without a cushion between herself and the grass, to better communicate the theme of her relationship to the earth (?).[5] Joseph is positioned higher in the image than Mary, although this is an unusual feature in compositions of the Holy Family. Mary is seated between his legs, as if he is protecting her, his great legs forming a kind of de facto throne. There is some debate as to whether Mary is receiving the Child from Joseph or vice versa.[6] Saint John the Baptist, the patron saint of Florence, is very commonly included in Florentine works depicting the Madonna and Child.[7] He is in the middle-ground of the painting, between the Holy Family and the background. The scene appears to be a rural one, with the Holy Family enjoying themselves on the grass and separated from the curiously (seemingly) unrelated group at the back by a low wall.
  The painting is still in its original frame, one that Michelangelo might have influenced or helped design.[8] The frame is ornately carved and rather unusual for the five heads it contains which protrude three-dimensionally into space. Similar to the nudes of the background, the meanings of these heads has been the subject of speculation. The frame also contains carvings of crescent moons, stars, vegetation, and lions’ heads. These symbols are, perhaps, references to the Doni and Strozzi families, taken from each one's coat of arms.[9] As depicted on the frame, “the moons are bound together with ribbons that interlock with the lions,” possibly referring to the marriage of the two families.[9]
  There is a horizontal band, possibly a wall, separating the foreground and background.[6][7][10] The background figures are five nudes, whose meaning and function are subject to much speculation and debate. Because they are much closer to us, the viewers, the Holy Family is much larger than the nudes in the background, a device to aid the illusion of deep space in a two-dimensional image. Behind Saint John the Baptist is a semi-circular ridge, against which the 'ignudi' are leaning, or upon which they are sitting. This semi-circle reflects or mirrors the circular shape of the painting itself and acts as a foil to the vertical nature of the principal group (the Holy family). Mary and Joseph gaze at Christ, but none of the background nudes looks directly at him.[11] The far background contains a mountainous landscape rendered in atmospheric perspective."""

  text_ita=""" La Gioconda, nota anche come Monna Lisa, è un dipinto a olio su tavola di legno di pioppo realizzato da Leonardo da Vinci, (77×53 cm e 13 mm di spessore), databile al 1503-1504 circa e conservato nel Museo del Louvre di Parigi.
  Opera iconica ed enigmatica della pittura mondiale, si tratta sicuramente del ritratto più celebre della storia nonché di una delle opere d'arte più note in assoluto. Il sorriso quasi impercettibile del soggetto, col suo alone di mistero, ha ispirato tantissime pagine di critica, letteratura, opere di immaginazione e persino studi psicoanalitici; sfuggente, ironica e sensuale, la Monna Lisa è stata di volta in volta amata e idolatrata, ma anche irrisa e vandalizzata.[1]
  La Gioconda viene ammirata ogni giorno da circa trentamila visitatori, ovvero l'80% dei visitatori del Museo del Louvre in cui è esposta,[2] tanto che nella grande sala in cui si trova, un cordone deve tenere a debita distanza le persone. Nella lunga storia del dipinto non sono infatti mancati i tentativi di vandalismo, nonché un furto rocambolesco, che ne hanno alimentato la popolarità.
  """
  
  #Exemple of questions for the QA task
  questions = ['Who is the subject?','who are the main characters?','what kind of message does the painting convey?']

  #QA, summary and translation results
  QAResults=[Information_Retrieval.QA_Bert(modello_QAandSum,text,question) for question in questions]
  summary=Information_Retrieval.summarize_Bert(modello_QAandSum,text,130,30)

  textITA=Information_Retrieval.translationITA_Bert(modello_ITATranslation, text)
  textEN=Information_Retrieval.translationEN_Bert(modello_ENTranslation, text_ita)